# --- History ---
HISTFILE="$HOME/.zsh_history"
HISTSIZE=32768
SAVEHIST=32768

setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
